/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package MorseCode

import kotlin.test.Test
import kotlin.test.assertEquals

class LibraryTest {
    @Test
    fun testEncode() {
        val lib = Library()

        assertEquals(".-", lib.encoder("A"),  "should encode character in Morse Code")
        assertEquals("- . ... -", lib.encoder("TEST"),  "should encode string in Morse Code")
        assertEquals("- . ... -", lib.encoder("test"),  "should encode lowercase string in Morse Code")
        assertEquals(".... . .-.. .-.. --- / .-- --- .-. .-.. -..", lib.encoder("HELLO WORLD"),  "should encode string in Morse Code")
    }
}
