/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package MorseCode

class Library {
    private val alphabet = MorseAlphabet()

    fun encoder(input: String): String {
        var str = ""

        input.forEach {
            str += alphabet.convertToMorse(it.toString()) + " "
        }

        return str.trim()
    }


}
