/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package MorseCode

class Library {
    private val morseAlphabet = Morse()
    private val alphabet = Alphabet()

    fun encoder(input: String): String {
        var str = ""

        input.forEach {
            str += morseAlphabet.convertToMorse(it.toString()) + " "
        }

        return str.trim()
    }

    fun decode(input: String): String {
        var str = ""
        val toDecode = input.split(" ")

        toDecode.forEach {
            str += alphabet.convertToAlphabet(it)
        }

        return str
    }
}
