/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package MorseCode

class Library {
    fun encoder(input: String): String {
        val alphabet = MorseAlphabet()
        var str = ""

        input.forEach {
            str += alphabet.convertToMorse(it.toString().toUpperCase()) + " "
        }

        return str.trim()
    }
}
